# test env manifest to setup dependencies under <west topdir>/dependencies
# should be initialized with west init -l config --mf west-standalone.yml
manifest:
  self:
    path: config
    import:
      file: west-dependency.yml
      path-prefix: dependencies