manifest:
  version: 1.2
  defaults:
    remote: cormoran
    revision: main
  remotes:
    - name: cormoran
      url-base: https://github.com/cormoran
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: sekigon-gonnoc
      url-base: https://github.com/sekigon-gonnoc
  projects:
    - name: zmk-west-commands
      import: true
    - name: zmk
      import:
        file: app/west.yml
      clone-depth: 1
      revision: v0.3-branch+dya
    - name: zmk-feature-non-lipo-battery-management
      remote: sekigon-gonnoc
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    - name: zmk-module-ble-management
    - name: zmk-module-battery-history
    - name: zmk-module-runtime-input-processor
    - name: zmk-module-settings-rpc
  self:
    path: config
